export const cities = [
  { "id": 1, "name": "Arica", "region_id": 1 },
  { "id": 2, "name": "Camarones", "region_id": 1 },
  { "id": 3, "name": "Putre", "region_id": 1 },
  { "id": 4, "name": "General Lagos", "region_id": 1 },

  { "id": 5, "name": "Iquique", "region_id": 2 },
  { "id": 6, "name": "Alto Hospicio", "region_id": 2 },
  { "id": 7, "name": "Pozo Almonte", "region_id": 2 },
  { "id": 8, "name": "Camiña", "region_id": 2 },
  { "id": 9, "name": "Colchane", "region_id": 2 },
  { "id": 10, "name": "Huara", "region_id": 2 },
  { "id": 11, "name": "Pica", "region_id": 2 },

  { "id": 12, "name": "Antofagasta", "region_id": 3 },
  { "id": 13, "name": "Mejillones", "region_id": 3 },
  { "id": 14, "name": "Sierra Gorda", "region_id": 3 },
  { "id": 15, "name": "Taltal", "region_id": 3 },
  { "id": 16, "name": "Calama", "region_id": 3 },
  { "id": 17, "name": "Ollagüe", "region_id": 3 },
  { "id": 18, "name": "San Pedro de Atacama", "region_id": 3 },
  { "id": 19, "name": "Tocopilla", "region_id": 3 },
  { "id": 20, "name": "María Elena", "region_id": 3 },

  { "id": 21, "name": "Copiapó", "region_id": 4 },
  { "id": 22, "name": "Caldera", "region_id": 4 },
  { "id": 23, "name": "Tierra Amarilla", "region_id": 4 },
  { "id": 24, "name": "Chañaral", "region_id": 4 },
  { "id": 25, "name": "Diego de Almagro", "region_id": 4 },
  { "id": 26, "name": "Vallenar", "region_id": 4 },
  { "id": 27, "name": "Freirina", "region_id": 4 },
  { "id": 28, "name": "Huasco", "region_id": 4 },
  { "id": 29, "name": "Alto del Carmen", "region_id": 4 },

  { "id": 30, "name": "La Serena", "region_id": 5 },
  { "id": 31, "name": "Coquimbo", "region_id": 5 },
  { "id": 32, "name": "Andacollo", "region_id": 5 },
  { "id": 33, "name": "La Higuera", "region_id": 5 },
  { "id": 34, "name": "Paihuano", "region_id": 5 },
  { "id": 35, "name": "Vicuña", "region_id": 5 },
  { "id": 36, "name": "Ovalle", "region_id": 5 },
  { "id": 37, "name": "Combarbalá", "region_id": 5 },
  { "id": 38, "name": "Monte Patria", "region_id": 5 },
  { "id": 39, "name": "Punitaqui", "region_id": 5 },
  { "id": 40, "name": "Río Hurtado", "region_id": 5 },
  { "id": 41, "name": "Illapel", "region_id": 5 },
  { "id": 42, "name": "Canela", "region_id": 5 },
  { "id": 43, "name": "Los Vilos", "region_id": 5 },
  { "id": 44, "name": "Salamanca", "region_id": 5 },

  { "id": 45, "name": "Valparaíso", "region_id": 6 },
  { "id": 46, "name": "Viña del Mar", "region_id": 6 },
  { "id": 47, "name": "Concón", "region_id": 6 },
  { "id": 48, "name": "Quilpué", "region_id": 6 },
  { "id": 49, "name": "Villa Alemana", "region_id": 6 },
  { "id": 50, "name": "Casablanca", "region_id": 6 },
  { "id": 51, "name": "Quintero", "region_id": 6 },
  { "id": 52, "name": "Puchuncaví", "region_id": 6 },
  { "id": 53, "name": "San Antonio", "region_id": 6 },
  { "id": 54, "name": "Cartagena", "region_id": 6 },
  { "id": 55, "name": "El Tabo", "region_id": 6 },
  { "id": 56, "name": "El Quisco", "region_id": 6 },
  { "id": 57, "name": "Algarrobo", "region_id": 6 },
  { "id": 58, "name": "Santo Domingo", "region_id": 6 }
]